### ISSUE TITLE
Cannot import detectors

### ISSUE THREAD

**Issue by XinDongol** [safellama/plexiglass#4]
I installed `plexiglass-1.0.9` with 
```
pip install plexiglass -U
```

Got some error when importing it
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0e3709df6528> in <module>
----> 1 from plexiglass.adversarial import FGSM, test_robustness
      2 import torch
      3 import timm
      4 from pprint import pprint
      5 import pytorchcv as ptcv

~/.local/lib/python3.6/site-packages/plexiglass/__init__.py in <module>
----> 1 from . import detectors
      2 from . import adversarial

ImportError: cannot import name 'detectors'
```

**Comment by enochkan** [comment]
@XinDongol thanks for bringing this to my attention. May I ask which Python version you're using? This issue may be related to the [circular import issue](https://github.com/enochkan/plexiglass/issues/2). Will try my best to push a fix by EoD today.

**Comment by XinDongol** [comment]
I am using `3.6.5`. Thanks

**Comment by enochkan** [comment]
@XinDongol Can you please try to download version `1.1.3` and see if the issue is resolved? Thanks!

**Comment by XinDongol** [comment]
`1.1.3` works well magically. Thanks for your rapid response.

**Comment by enochkan** [comment]
@XinDongol no problem at all. Thanks for letting me know. You are totally welcome to contribute as well 👍
