### ISSUE TITLE
File indicating version does not exist when installing from pypi

### ISSUE THREAD

**Issue by jskartzman** [safellama/plexiglass#6]
File indicating version number is in all caps while the file listed in the setup.py file is all lowercase.  As a result, it's not installing properly from PyPI.  Package installation from github works though.  PyPI distribution should be updated

**Comment by enochkan** [comment]
Hi @jkartzman thanks for bringing this to my attention. I have pushed the latest version `1.2.0` to PYPI, it should contain the lower case version file. Let me know if it works and I'll close the issue :)

**Comment by jskartzman** [comment]
Works great now!
